// Generated by scripts/generate-asset-manifest.mjs — do not edit by hand.
// Drop logo.svg (or .png, .webp) into public/brand, and logo-white.* for the
// version used over dark sections. Rewritten on the next `npm run dev` or
// `npm run build`.
export const LOGO_SRC: string | null = '/brand/logo.png';
export const LOGO_WHITE_SRC: string | null = '/brand/logo-white.png';
