// Generated by scripts/generate-asset-manifest.mjs — do not edit by hand.
// Drop a file called logo.svg (or .png, .webp) into public/brand and this is
// rewritten on the next `npm run dev` or `npm run build`.
export const LOGO_SRC: string | null = null;
