// Generated by scripts/generate-floating-manifest.mjs — do not edit by hand.
// Add or remove files in public/floating and this is rewritten on the next
// `npm run dev` or `npm run build`.
export type FloatingMedia = { src: string; kind: 'image' | 'video' };

export const FLOATING_MEDIA: FloatingMedia[] = [];
