// Generated by scripts/generate-asset-manifest.mjs — do not edit by hand.
// Add or remove files in public/steps and this is rewritten on the next
// `npm run dev` or `npm run build`.
export type StepMedia = { src: string; kind: 'image' | 'video' };

export const STEP_MEDIA: StepMedia[] = [
  { src: '/steps/step1-animation.webm', kind: 'video' },
  { src: '/steps/step2-animation.webm', kind: 'video' },
  { src: '/steps/step3-animation.webm', kind: 'video' },
];
